# =========================
# Training Configuration
# =========================

training:
  batch_size: 2
  epochs: 20
  learning_rate: 0.0001
  num_workers: 0
  shuffle: false
  pin_memory: true
  drop_last: true
  scheduler_step_size: 15

# =========================
# Model Configuration
# =========================

model:
  encoder:
    type: ResnetEncoder
    num_layers: 50
    pretrained: true

  depth_decoder:
    type: DepthDecoder

  semantic_decoder:
    type: SemanticDecoder
    num_classes: 29

  pose_net:
    type: PoseNet
    num_layers: 50
    num_input_images: 2
    pretrained: true

# =========================
# Geometry / Projection
# =========================

geometry:
  image_height: 192
  image_width: 640
  scales: [0, 1, 2, 3]
  frames: [0, -1, 1]

# =========================
# Loss Configuration
# =========================

loss:
  use_ssim: true
  ssim_weight: 0.85
  l1_weight: 0.15
  smoothness_weight: 0.001

# =========================
# Dataset Configuration
# =========================

virtual_dataset:
  name: CarlaDataset
  root_dir: F:\\CARLA_0.9.16\\PythonAPI\\carla_data_tools\\carla_dataset
  img_height: 192
  img_width: 640
  depth: true
  semantic: true
  min_depth: 0.1
  max_depth: 100.0

# =========================
# Runtime
# =========================

runtime:
  device: cuda   # auto | cpu | cuda

tensorboard:
  log_loss_freq: 10
  log_img_freq: 500