# =========================
# Training Configuration
# =========================

training:
  batch_size: 16
  epochs: 20
  learning_rate: 0.0001
  num_workers: 4
  shuffle: true
  pin_memory: true
  drop_last: true
  scheduler_step_size: 15

# =========================
# Model Configuration
# =========================

model:
  encoder:
    type: ResnetEncoder
    num_layers: 101
    pretrained: true

  depth_decoder:
    type: DepthDecoder

  pose_net:
    type: PoseNet
    num_layers: 18
    num_input_images: 2
    pretrained: true

# =========================
# Geometry / Projection
# =========================

geometry:
  image_height: 192
  image_width: 640
  scales: [0, 1, 2, 3]

# =========================
# Loss Configuration
# =========================

loss:
  use_ssim: true
  ssim_weight: 0.85
  l1_weight: 0.15
  smoothness_weight: 0.001

# =========================
# Dataset Configuration
# =========================

dataset:
  name: TestDataset
  csv_path: eigen_full_train.csv
  root_dir: carla_dataset
  img_height: 192
  img_width: 640

# =========================
# Runtime
# =========================

runtime:
  device: cuda   # auto | cpu | cuda

tensorboard:
  log_loss_freq: 10
  log_img_freq: 500